### ISSUE TITLE
Go Rewrite

### ISSUE THREAD

**Issue by jfhbrook** [jfhbrook/dosapp#1]
`dosapp` is currently written in bash. However, I wrote it using `go-task` and `gomplate`, with the intent of rewriting it in go. Using go is desirable because it would end with a static binary with `go-task` and template functionality embedded - in other words, no dependencies.

### Milestone 1: Working rewrite

At the end of this milestone, I should have a POC that can do everything bash DOSAPP can do, minus issues with package handling and templating. It won't be ready to merge, but it will be complete enough for the second milestone.

- [x] Create cobra app with the same shape as the bash command
- [X] Choose logging stack
- [X] load-config
- [x] Set almost sensible default for packages directory
- [x] Hard-code packages directory in main env config to my repo
- [x] Move log level code to root `PersistentPreRun`
- [x] edit-config
- [x] refresh-main
- [x] run-init
  - [x] Embed dosapp.env and Taskfile in config.go
  - [x] Check if dosapp.env exists
  - [x] Write template dosapp.env to config home
- [x] run app task with `exec.Command`
- [x] run-root
- [x] App struct
  - [x] Init (init-app-config)
  - [x] Refresh
  - [x] Readme (show-readme)
- [x] get app name from arguments
- [x] Inject config into editor/pager
- [x] run-install
  - need to solve some templating problems
- [x] App.Installed()
- [x] run-start
- [x] run-link
- [x] run-remove-link
- [x] run-remove
  - [x] rm -rf app

### Milestone 2: embed templating

One big problem at the end of milestone 1 is that templates still require accessing the config directory in the source root. But those templates are accessed by go-task, so their rendering needs to be exposed on the command line interface.

At the end of this milestone, not only should I not need DOSAPP_ROOT anymore; I shouldn't need `gomplate` either.

- [x] Create `template` command that replaces gomplate
- [x] Embed config files as filesytem for `template` command
- [x] Clean up DOSAPP_ROOT

### Milestone 3: package support + initial release

At the end of this milestone, I won't need to hard-code the package or root directories anymore, and I'll be a `go` for release. 

- [x] add registry to config
- [x] pull github releases
- [x] grab the latest release matching the app
- [x] download the app to `~/.cache/dosapp/packages`
- [x] unpack tar file to `~/.local/share/dosapp/packages` (preferably native)
- [x] run-fetch
  - includes lots of business logic and fs checks
  - call directly from run-install but also expose as separate commands
- [x] clean up DOSAPP_PACKAGE_HOME
- [x] load package yml
  - [x] validate package yaml, use idiomatic go errors
- [x] pack tar file (preferably native)
- [x] exec gh-release `gh release create`
- [x] run-publish
- [ ] uninstall, publish and install packages until they all work
- [x] update install instructions to use `go install`

**Comment by jfhbrook** [comment]
Copilot suggested a shell formatter that's part of this go package:

https://github.com/mvdan/sh

But it also has a small shell interpreter - this might be a useful tool to embed into dosapp.

**Comment by jfhbrook** [comment]
A challenge with go is that the bin isn't in a well-known location compared to the packages. While I can manually set that path during configuration, in practice I'll need to solve for remote packages before I complete this rewrite.

**Comment by jfhbrook** [comment]
I implemented the package publishing half of the equation in bash, so I have remote packages to work against in the go implementation.

That said, I'm going to target a first milestone that replicates the bash functionality with the packages directory set manually. Once everything else works, I can implement package fetch functionality, reimplement publish in go, and be ready for an initial release.

**Comment by jfhbrook** [comment]
I was hoping to punt on templating until I got the basics of the go port working. But I need templating to set up app configs. Note that I *don't* need the same templating for core configs, as implemented in bash.

I have two choices:

1. Implement templating directly
  - An `Env` method which populates a map instead of an array
  - Learn/implement [text/template](https://pkg.go.dev/text/template)
  - Exposing as a command not required, but easy
  - A good exercise, would learn more this way
2. Exec gomplate, as I'm doing now
  - Chintzy
  - Easy to copy from Bash
  - Can replace with direct templating in Milestone 3

I'm tempted to go with the latter in the name of expediency, but it feels bad.

**Comment by jfhbrook** [comment]
Some issues with the way I'm using env vars:

1. They override externally set env vars
2. They don't respect variables, nor do they expand tilde

I could solve these by using godotenv's `Read` function to get a map, and parsing with mvdan/sh respectively. But if I'm already this deep, maybe I should switch to a yaml/template config format?

**Comment by jfhbrook** [comment]
This work is done, it just needs QA and a merge.
